#pragma config(StandardModel, "RVW Buggybot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
Turning with Gyroscope
This program instructs your robot turn to the right until the desired number of degrees has been reached,
stop for two seconds, then turn to the left for until the desired number of degrees has been reached.
There is a two second pause at the beginning of the program.

Robot Model(s): NXT REMBOT

[I/O Port]          [Name]              [Type]                [Description]
Motor Port 2        rightMotor          NXT Motor             Right side motor
Motor Port 3        leftMotor           NXT Motor             Left side motor
Sensor Port 2     	gyro				        HiTechnic Gyro

----------------------------------------------------------------------------------------------------*/

// This program turns the robot right for a specified 'degrees', stops the robot for two seconds,
// then turns to the left for the same amount of 'degrees'.

task main()
{
  wait1Msec(2000);
  int firstdegrees = 90;
  int threshold = 35;// 'degrees' is how many degrees we want to turn

  int goals = 25;
 // 'goal' is be the current gyro reading + our turning degrees



 // 'goal' is be the current gyro reading - our turning degrees

  while(SensorValue[sonar] > goals)   		 // while the gyro sensor reading is less than our goal:
  {
																				 // turn LEFT in place (point turn):
    motor[rightMotor] = 	127;            // set motorB to speed 20
    motor[leftMotor]  =  127;            // set motorC to speed -20
  }
  motor[rightMotor] = 	0;            // set motorB to speed 20
  motor[leftMotor]  =  0;
  wait1Msec(2000);
  int degrees = 900;                     // 'degrees' is how many degrees we want to turn

  int goal = (SensorValue[gyro] + degrees);
  bool isnotred = true  ;// 'goal' is be the current gyro reading + our turning degrees

  while(SensorValue[gyro] < goal)   		// while the gyro sensor reading is less than our goal:
  {
																				// turn RIGHT in place (point turn):
    motor[rightMotor] = -20;           	// set motorB to speed -20
    motor[leftMotor]  =  20;            // set motorC to speed 20
  }


  ClearTimer(T1);
  while(sensorValue[gyro] < 1690)
  {
    // sensor sees light:
    if(SensorValue(light) < threshold)
    {
      // counter-steer left:
      motor[leftMotor]  = 35;
      motor[rightMotor] = 5;
    }
    // sensor sees dark:
    else
    {
      // counter-steer right:
      motor[leftMotor]  = 5;
      motor[rightMotor] = 35;
    }

  }
  motor[leftMotor]  = 0;
  motor[rightMotor] = 0;
  wait1Msec(1000);


  ClearTimer(T1);
  while(time1[T1] < 3497)// speed= distance/timetaken 19.6/50
  {
  	motor[leftMotor]  = 70;
  	motor[rightMotor] = 70;
  }

  motor[leftMotor]  = 0;
  motor[rightMotor] = 0;

  while(SensorValue(sonar) >26)
  {
    // sensor sees light:
    if(SensorValue(light) < threshold)
    {
       // counter-steer right:
      motor[leftMotor]  = 5;
      motor[rightMotor] = 35;
    }
    // sensor sees dark:
    else
    {  // counter-steer left:
      motor[leftMotor]  = 35;
      motor[rightMotor] = 5;
    }
  }

 goal = 42;
 goal = (SensorValue[gyro] + degrees);
 while(SensorValue[gyro] < goal)   		// while the gyro sensor reading is less than our goal:
  {
																				// turn RIGHT in place (point turn):
    motor[rightMotor] = -20;           	// set motorB to speed -20
    motor[leftMotor]  =  0;


  }
   motor[rightMotor] = 0;           	// set motorB to speed -20
   motor[leftMotor]  =  0;
    goals = 20


  while(SensorValue[sonar] > goals)   		 // while the gyro sensor reading is less than our goal:
  {
																				 // turn LEFT in place (point turn):
    motor[rightMotor] = 	127;            // set motorB to speed 20
    motor[leftMotor]  =  127;            // set motorC to speed -20
  }
   goal = 70
   while(SensorValue[sonar] < goal)
 {
   motor[rightMotor] = 	20;            // set motorB to speed 20
   motor[leftMotor]  =  -20;
   }
   while(SensorValue[sonar] > goals)   		 // while the gyro sensor reading is less than our goal:
  {
																				 // turn LEFT in place (point turn):
    motor[rightMotor] = 	127;            // set motorB to speed 20
    motor[leftMotor]  =  127;            // set motorC to speed -20
  }
   while(SensorValue[sonar] < goal)
 {
   motor[rightMotor] = 	20;            // set motorB to speed 20
   motor[leftMotor]  =  -20;
   }

    while(SensorValue[sonar] < goal)
 {
   motor[rightMotor] = 	20;            // set motorB to speed 20
   motor[leftMotor]  =  -20;
   }
  int end = 24;
  ClearTimer(T1);


  motor[rightMotor] = 0;
   motor[leftMotor]  = 0;
  wait1Msec(2000);
  while(SensorValue(sonar) > end )
  {
    // sensor sees light:
    if(SensorValue(light) < threshold)
    {
      // counter-steer left:
      motor[leftMotor]  = 35;
      motor[rightMotor] = 5;
    }
    // sensor sees dark:
    else
    {
      // counter-steer right:
      motor[leftMotor]  = 5;
      motor[rightMotor] = 35;
    }
  }

    while(SensorValue(gyro) < 10){

  	motor[leftMotor]  = 20;
    motor[rightMotor] = -20;
    }
    while(SensorValue(sonar) > 30){

  	motor[leftMotor]  = 40;
    motor[rightMotor] = 40;
    }
    motor[leftMotor]  = 0;
    motor[rightMotor] = 0;





}
